#Display message to the standart output
print("System failure Imminent!")
print("System reboot has been initiated...")
print("\n...rebooting sensory system")
print("...rebooting output motors")
print("...rebooting hover Engine")
print("\nSystem Online")
print("I am a beep!")


# Display a box
print("\n      ##########")
print("      #        #")
print("      # #   #  #")
print("      #   __   #")
print("      #        #")
print("      ##########")
print("         ####")
print("      ##########")
print("------#        #------")
print("      #        #")
print("      ##########")
print("      #        #")
print("      #        #")
print("      #        #")